# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180509_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_second',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
